config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/', to: 'pages#home'
  get '/personal', to: 'pages#personal'
  get '/users/update_info', to: 'users#update_info'
  get '/users/update_matches', to: 'users#update_matches'
  get '/profile/:id', to: 'pages#profile'

  get '/conversations', to: 'conversations#index'
  get '/conversations/:id', to: 'conversations#show'
  post '/conversations/create', to: 'conversations#create'
  post '/conversations/:id/messages/create', to: 'conversations#add_message'

end

app/views/pages/chat.html.erb
<body id="chat">

  <!-- <div id="header">
    <h1> L2T </h1>
    <nav>
      <%= link_to 'SIGN OUT', '/users/sign_out', :method => :delete %>
    </nav>
  </div> -->

<iframe src="http://deadsimplechat.com/+cDPYw" frameborder="0"width="800px" height="600px"></iframe>


 <!--  <div id="footer"></div> -->

</body>

app/views/pages/personal.html.erb
<body id="personal">

  <div id="header">
    <h1><%= link_to 'L2T', '/' %></h1>
    <nav>
      <%= link_to 'SIGN OUT', '/users/sign_out', :method => :delete %>
    </nav>
  </div>

  <div id="info">

    <div id="pic">
      <a href="/profile/<%=@personal_info[:user_id]%>"><img id="profile-img" class="vertalign" src="<%=@personal_info[:image_url]%>" /></a>
    </div>

    <div id="about">
      <%= link_to 'INBOX', '/conversations' %>
      <div id="personal-box">
        <h3><%=@personal_info[:name]%></h3>
        <p><%=@personal_info[:blurb]%></p>
      </div>
    </div>

    <div id="map">
      <img src="http://static2.stuff.co.nz/1397882814/958/9959958.jpg">
    </div>

  </div>

  <div id="feed">

    <div id="news">

      <% unless @personal_info[:tweets].empty? %>
        <div class="personal-media">
            <h2>TWEETS</h2>
            <% @personal_info[:tweets].each do |tweet|%>
              <li id="li-padding"><%=tweet.content%></li>
            <% end %>
        </div>
      <% end %>

      <% unless @personal_info[:videos].empty? %>
        <div class="personal-media">
            <h2>VIDEOS</h2>
            <% @personal_info[:videos].each do |video|%>
              <li id="li-padding"><a href='<%=video.url%>'><%=video.title%></a></li>
            <% end %>
        </div>
      <% end %>

      <% unless @personal_info[:tracks].empty? %>
        <div class="personal-media">
            <h2>TRACKS</h2>
            <% @personal_info[:tracks].each do |track|%>
              <li id="li-padding"><a href='<%=track.track_url%>'><%=track.title%></a></li>
            <% end %>
        </div>
      <% end %>

    </div>

    <div id="matches">
      <ul>
        <h2>MATCHES</h2>
        <% @match_data.each do |match| %>
          <li class="match">
            <div id="match-img">
              <a href="/profile/<%=match["id"]%>">
                <img src="<%=match["image_url"]%>" class='vertalign' />
              </a>
            </div>
            <div id="match-info">
              <h3><%=match["name"]%></h3>
              <p><%=match["blurb"]%></p>
            </div>
            <div id="match-percent">
              <div class="vertalign">
                <p><%=match["overall_percent"]%></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

  </div>

  <div id="footer"></div>

</body>

app/views/pages/profile.html.erb
<body id="profile">

  <div id="header">
    <h1><%= link_to 'L2T', '/' %></h1>
    <nav>
        <%= link_to 'SIGN OUT', '/users/sign_out', :method => :delete %>
    </nav>
  </div>

  <div id="info">

    <div id="pic">
      <img id="profile-img" class="vertalign" src="<%=@personal_info[:image_url]%>" />
    </div>

    <div id="about">
      <div id="personal-box">
        <h3><%=@personal_info[:name]%></h3>
        <p><%=@personal_info[:blurb]%></p>
        <%= link_to 'START CONVERSATION', conversations_create_path(@ids, user_1_id: current_user.id, user_2_id: @personal_info[:user_id]), :method => :post %>
      </div>
    </div>

    <div id="map">
<!--       <img src="http://static2.stuff.co.nz/1397882814/958/9959958.jpg"> -->
    </div>

  </div>

  <div id="profile-feed">
    <% unless @personal_info[:tweets].empty? %>
      <div class="personal-media">
          <h2>TWEETS</h2>
          <% @personal_info[:tweets].each do |tweet|%>
            <li id="li-padding"><%=tweet.content%></li>
          <% end %>
      </div>
    <% end %>

    <% unless @personal_info[:videos].empty? %>
      <div class="personal-media">
          <h2>VIDEOS</h2>
          <% @personal_info[:videos].each do |video|%>
            <li id="li-padding"><a href='<%=video.url%>'><%=video.title%></a></li>
          <% end %>
      </div>
    <% end %>

    <% unless @personal_info[:tracks].empty? %>
      <div class="personal-media">
          <h2>TRACKS</h2>
          <% @personal_info[:tracks].each do |track|%>
            <li id="li-padding"><a href='<%=track.track_url%>'><%=track.title%></a></li>
          <% end %>
      </div>
    <% end %>
  </div>


  <div id="footer"></div>

</body>